// Regenerates src/render/bodyMapMasks.ts: the body map (front + back, male and female) rasterized
// once into two planes per figure -- which part each pixel belongs to, and how much of it (the
// anti-aliased edge) -- so the Worker can draw a coloured body map for the weekly digest by only
// blending colours (src/render/bodyMapPng.ts). Run after bumping react-muscle-highlighter:
//   node --import tsx scripts/build-bodymap-masks.ts
import { writeFileSync } from "node:fs";
import { deflateSync } from "node:zlib";
import { VIEW, figureParts, paint, type Pt } from "../src/render/rasterize";

const FIGURE_HEIGHT = 360;
const PAD = 16;
const SLUGS = [
  "abs", "adductors", "ankles", "biceps", "calves", "chest", "deltoids", "feet", "forearm", "gluteal", "hamstring",
  "hands", "hair", "head", "knees", "lower-back", "neck", "obliques", "quadriceps", "tibialis", "trapezius", "triceps", "upper-back",
];

function build(sex: "male" | "female") {
  const views = (["front", "back"] as const).map((side) => ({ side, box: VIEW[sex][side] }));
  const scale = FIGURE_HEIGHT / Math.max(...views.map((v) => v.box[3]));
  const widths = views.map((v) => Math.ceil(v.box[2] * scale));
  const w = widths[0]! + widths[1]! + PAD * 3;
  const h = FIGURE_HEIGHT + PAD * 2;
  // Every part's polygons in image space, both views.
  const bySlug = new Map<string, Pt[][]>();
  let ox = PAD;
  views.forEach((v, idx) => {
    const [vx, vy] = v.box;
    for (const part of figureParts(sex, v.side)) {
      const polys = part.polys.map((poly) => poly.map(([x, y]) => [ox + (x - vx) * scale, PAD + (y - vy) * scale] as Pt));
      bySlug.set(part.slug, [...(bySlug.get(part.slug) ?? []), ...polys]);
    }
    ox += widths[idx]! + PAD;
  });
  const label = new Uint8Array(w * h);
  const alpha = new Uint8Array(w * h);
  for (const [slug, polys] of bySlug) {
    const idx = SLUGS.indexOf(slug);
    if (idx < 0) throw new Error(`unknown slug ${slug}`);
    const rgb = new Uint8Array(w * h * 3);
    paint(rgb, w, h, [{ polys, rgb: [255, 255, 255] }]);
    for (let i = 0; i < w * h; i++) {
      const a = rgb[i * 3]!;
      if (a > alpha[i]!) { alpha[i] = a; label[i] = idx + 1; }
    }
  }
  const packed = new Uint8Array(w * h * 2);
  packed.set(label, 0);
  packed.set(alpha, w * h);
  return { w, h, data: deflateSync(packed, { level: 9 }).toString("base64") };
}

const male = build("male");
const female = build("female");
writeFileSync(
  new URL("../src/render/bodyMapMasks.ts", import.meta.url),
  `// Generated by scripts/build-bodymap-masks.ts from react-muscle-highlighter's paths -- do not edit.
// Per figure: zlib(label plane (0 = background, else SLUGS index + 1) ++ alpha plane), w × h each.
export const SLUGS = ${JSON.stringify(SLUGS)};
export const MASKS = {
  male: { w: ${male.w}, h: ${male.h}, data: "${male.data}" },
  female: { w: ${female.w}, h: ${female.h}, data: "${female.data}" },
} as const;
`,
);
console.log("male", male.w, "x", male.h, male.data.length, "b64 chars; female", female.w, "x", female.h, female.data.length);
